version: '3.8'
services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.serverjs
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    stdin_open: true
    tty: true
