export const emojiList = [
{names: ['kekwait'], imgUrl: 'custom_emojis/Kek Emojis pack/7285-kekwait.png', id: '7285'},
{names: ['pepe'], imgUrl: 'custom_emojis/Kek Emojis pack/9879_pepe_kek.gif', id: '9879'},
{names: ['TrollKEK'], imgUrl: 'custom_emojis/Kek Emojis pack/9303_TrollKEK.png', id: '9303'},
{names: ['pepe'], imgUrl: 'custom_emojis/Kek Emojis pack/8554_pepe_kek.png', id: '8554'},
{names: ['KEKW'], imgUrl: 'custom_emojis/Kek Emojis pack/4566_KEKW.png', id: '4566'},
{names: ['topkek'], imgUrl: 'custom_emojis/Kek Emojis pack/7785_topkek.gif', id: '7785'},
{names: ['OmegaKek'], imgUrl: 'custom_emojis/Kek Emojis pack/2717_OmegaKek.png', id: '2717'},
{names: ['kekw'], imgUrl: 'custom_emojis/Kek Emojis pack/1314-kekw-holup.gif', id: '1314'},
{names: ['dogekek'], imgUrl: 'custom_emojis/Kek Emojis pack/6358_dogekek.gif', id: '6358'},
{names: ['kekw'], imgUrl: 'custom_emojis/Kek Emojis pack/5658_kekw.png', id: '5658'},
{names: ['keka'], imgUrl: 'custom_emojis/Kek Emojis pack/2236_keka.gif', id: '2236'},
{names: ['smekw'], imgUrl: 'custom_emojis/Kek Emojis pack/3756-smekw.png', id: '3756'},
{names: ['KEKL'], imgUrl: 'custom_emojis/Kek Emojis pack/1822_KEKL.png', id: '1822'},
{names: ['keknessa'], imgUrl: 'custom_emojis/Kek Emojis pack/7819_keknessa.png', id: '7819'},
{names: ['KEK4K'], imgUrl: 'custom_emojis/Kek Emojis pack/1128_KEK4K.png', id: '1128'},
{names: ['pepes'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/3074-pepes-x.gif', id: '3074'},
{names: ['peepobeanbag'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/6881-peepobeanbag.gif', id: '6881'},
{names: ['pepedance'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/3184-pepedance.gif', id: '3184'},
{names: ['peepocomfyhd'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/8032-peepocomfyhd.gif', id: '8032'},
{names: ['revivedge'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/8806-revivedge.png', id: '8806'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/2332-pepe-angry-kid.png', id: '2332'},
{names: ['okayge'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/1321-okayge.png', id: '1321'},
{names: ['pepepoggerditto'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/3254-pepepoggerditto.gif', id: '3254'},
{names: ['pepeban'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/4363-pepeban.png', id: '4363'},
{names: ['jammies'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/3880-jammies.gif', id: '3880'},
{names: ['peeposhy'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/7493-peeposhy.gif', id: '7493'},
{names: ['vibepepe'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/5120-vibepepe.png', id: '5120'},
{names: ['peepoblankethd'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/5366-peepoblankethd.png', id: '5366'},
{names: ['peped'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/9056-peped.gif', id: '9056'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/8399-pepe-fuck-you.png', id: '8399'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/2620-pepe-60.gif', id: '2620'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/4297-pepe-hacker.gif', id: '4297'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/3613-pepe-with-jesus.png', id: '3613'},
{names: ['peepfeetw'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/1697-peepfeetw.gif', id: '1697'},
{names: ['pepesadrain'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/9542-pepesadrain.gif', id: '9542'},
{names: ['happy'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/1636-happy-pepe.png', id: '1636'},
{names: ['pepecuddle'], imgUrl: 'custom_emojis/Pepe emoji pack (1)/5407-pepecuddle.gif', id: '5407'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/4114-pepe-why.png', id: '4114'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/1913-pepe-sadhugs.png', id: '1913'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/6205-pepe-sad.png', id: '6205'},
{names: ['pepehands'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/8552-pepehands.png', id: '8552'},
{names: ['peepoteddycrying'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/9240-peepoteddycrying.png', id: '9240'},
{names: ['pepef'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/2901-pepef.png', id: '2901'},
{names: ['pepecry'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/2982-pepecry.png', id: '2982'},
{names: ['pepesaddrawing'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/1934-pepesaddrawing.png', id: '1934'},
{names: ['pepesadge'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/6931-pepesadge.png', id: '6931'},
{names: ['pepebored'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/1148-pepebored.png', id: '1148'},
{names: ['pepesadcry'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/5413-pepesadcry.png', id: '5413'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/2481-pepe-feelsbadman.gif', id: '2481'},
{names: ['peepotired'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/1649-peepotired.png', id: '1649'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/2364-pepe-hug.png', id: '2364'},
{names: ['pepesob'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/2022-pepesob.gif', id: '2022'},
{names: ['feelsweakman'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/8169-feelsweakman.gif', id: '8169'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/3178-pepe-suffering.png', id: '3178'},
{names: ['peepopillow'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/5918-peepopillow.png', id: '5918'},
{names: ['feelsweakman'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/9548-feelsweakman.png', id: '9548'},
{names: ['sadge'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/4838-sadge.png', id: '4838'},
{names: ['sadpepecrypet'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/2998-sadpepecrypet.gif', id: '2998'},
{names: ['sad'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/7301-sad-pepe-cat.png', id: '7301'},
{names: ['hugers'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/1138-hugers.png', id: '1138'},
{names: ['pepehang'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/2853-pepehang.png', id: '2853'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/9421-pepe-tinyviolin.gif', id: '9421'},
{names: ['feelsbadmane'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/3912-feelsbadmane.png', id: '3912'},
{names: ['pepeold'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/6455-pepeold.png', id: '6455'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/9133-pepe-tinyviolin.png', id: '9133'},
{names: ['peeposadblanket'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/4892-peeposadblanket.png', id: '4892'},
{names: ['pepecuerda'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/3562-pepecuerda.png', id: '3562'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe Sad Emoji Pack/5232-pepe-pet.gif', id: '5232'},
{names: ['pepefiendish'], imgUrl: 'custom_emojis/Pepe Emoji Pack/3321-pepefiendish.png', id: '3321'},
{names: ['hymoji'], imgUrl: 'custom_emojis/Pepe Emoji Pack/5696-hymoji-3036peeposus.png', id: '5696'},
{names: ['stretcheyes'], imgUrl: 'custom_emojis/Pepe Emoji Pack/2189-stretcheyes.png', id: '2189'},
{names: ['pepehands'], imgUrl: 'custom_emojis/Pepe Emoji Pack/5441-pepehands-waa.png', id: '5441'},
{names: ['pepethinking'], imgUrl: 'custom_emojis/Pepe Emoji Pack/1621-pepethinking.png', id: '1621'},
{names: ['pepepunch1'], imgUrl: 'custom_emojis/Pepe Emoji Pack/5937_pepepunch1.png', id: '5937'},
{names: ['runtowards'], imgUrl: 'custom_emojis/Pepe Emoji Pack/2707-runtowards.png', id: '2707'},
{names: ['pepecuss'], imgUrl: 'custom_emojis/Pepe Emoji Pack/7960-pepecuss.png', id: '7960'},
{names: ['oldge'], imgUrl: 'custom_emojis/Pepe Emoji Pack/1137-oldge.png', id: '1137'},
{names: ['bruh'], imgUrl: 'custom_emojis/Pepe Emoji Pack/4919-bruh-pepe.png', id: '4919'},
{names: ['pepeohno'], imgUrl: 'custom_emojis/Pepe Emoji Pack/2290-pepeohno.png', id: '2290'},
{names: ['pepestaring'], imgUrl: 'custom_emojis/Pepe Emoji Pack/7165-pepestaring.png', id: '7165'},
{names: ['prayge'], imgUrl: 'custom_emojis/Pepe Emoji Pack/4437-prayge.png', id: '4437'},
{names: ['pepesob'], imgUrl: 'custom_emojis/Pepe Emoji Pack/2374-pepesob.png', id: '2374'},
{names: ['pepeyes'], imgUrl: 'custom_emojis/Pepe Emoji Pack/4811-pepeyes.png', id: '4811'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe Emoji Pack/7587-pepe-simp.gif', id: '7587'},
{names: ['pepposad'], imgUrl: 'custom_emojis/Pepe Emoji Pack/9271-pepposad.png', id: '9271'},
{names: ['peepo'], imgUrl: 'custom_emojis/Pepe Emoji Pack/9958-peepo-riot.gif', id: '9958'},
{names: ['weirdge'], imgUrl: 'custom_emojis/Pepe Emoji Pack/9731-weirdge.png', id: '9731'},
{names: ['pepehattip'], imgUrl: 'custom_emojis/Pepe Emoji Pack/9291-pepehattip.gif', id: '9291'},
{names: ['nervous'], imgUrl: 'custom_emojis/Pepe Emoji Pack/1602-nervous.png', id: '1602'},
{names: ['pepeclap'], imgUrl: 'custom_emojis/Pepe Emoji Pack/3550-pepeclap.png', id: '3550'},
{names: ['dumbpepe'], imgUrl: 'custom_emojis/Pepe Emoji Pack/9115-dumbpepe.png', id: '9115'},
{names: ['pepecash'], imgUrl: 'custom_emojis/Pepe Emoji Pack/7530-pepecash.png', id: '7530'},
{names: ['teasing'], imgUrl: 'custom_emojis/Pepe Emoji Pack/7958-teasing-pepe.gif', id: '7958'},
{names: ['pepecrazyguns'], imgUrl: 'custom_emojis/Pepe Emoji Pack/5445-pepecrazyguns.png', id: '5445'},
{names: ['pepeparty'], imgUrl: 'custom_emojis/Pepe Emoji Pack/3469-pepeparty.gif', id: '3469'},
{names: ['copium'], imgUrl: 'custom_emojis/Pepe Emoji Pack/1409-copium-overdose-pepe.gif', id: '1409'},
{names: ['peepo'], imgUrl: 'custom_emojis/Pepe Emoji Pack/7483-peepo-rich.gif', id: '7483'},
{names: ['wicked'], imgUrl: 'custom_emojis/Pepe Emoji Pack/5532-wicked-steer.gif', id: '5532'},
{names: ['pepe'], imgUrl: 'custom_emojis/Pepe Emoji Pack/8276-pepe-caught.gif', id: '8276'},
{names: ['stonedyay'], imgUrl: 'custom_emojis/Pepe Emoji Pack/5058-stonedyay.png', id: '5058'},
]
